### ISSUE TITLE
manual install or carthage setup?

### ISSUE THREAD

**Issue by sirvon** [cesteban/ASDKFluentExtensions#1]
Thanks for this.
Anyone to install this manually or via carthage?

**Comment by cesteban** [comment]
Sorry for the (**very**) late reply @sirvon ! Until today this was more or less a personal repo, and I wasn't even subscribed to notifications! 😓

As explained in the README, Carthage is currently not supported. The reason is that the project is using Cocoapods internally, so supporting Carthage distribution is not immediate. But if there is interest, I can totally move the project to use Carthage, so it would be available for both Cocoapods and Carthage. I'll keep you updated.

On the meanwhile, you can clone the repo and add the categories to your project manually if you want to play with them. Anyway, as I said, Carthage will be available really soon.

Thank you very much for your feedback, and my apologies once more for the extremely late reply.

**Comment by cesteban** [comment]
Done. Carthage is supported form version 0.6 of ASDKFluentExtensions. Please @sirvon check everything is correct. I tested the build from another project but I'm not an expert on Carthage, so please let me know if you miss something.

**Comment by cesteban** [comment]
Closing this for the moment, please reopen it if you think it is necessary.
